server:
  port: 8080

spring:
  application:
    name: aiforge-web
  datasource:
    # 替换为你自己的数据库名、用户名和密码
    url: jdbc:mysql://localhost:3306/aiforge?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234567
      database: 6
      lettuce:
        pool:
          max-active: 8

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    # 在控制台打印 SQL 语句，开发阶段必开，排错神器
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名自动映射 (如数据库 user_name 自动映射到实体类 userName)
    map-underscore-to-camel-case: true

# 文件上传配置
spring.servlet.multipart:
  max-file-size: 50MB
  max-request-size: 100MB

# AiForge 自定义配置
aiforge:
  file:
    storage-path: E:/Develop/aiforge/aiforge-server/uploads